#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

install() {
  # set up desktop environment
  yay --needed --noconfirm -S \
    xorg-server xorg-xrandr xorg-xinit xdotool \
    rxvt-unicode rxvt-unicode-terminfo \
    ttf-fira-{mono,sans} ttf-font-awesome tamsyn-font siji-git \
    lightdm lightdm-mini-greeter \
    bspwm sxhkd compton dunst xcb-proto polybar libnotify \
    arc-gtk-theme qt5-styleplugins
  sudo systemctl enable lightdm
  sudo sed -i \
    -e "s@^#\?\(greeter-session=\).\+@\1lightdm-mini-greeter@" \
    -e "s@^#\?\(user-session=\).\+@\1bspwm@" \
    /etc/lightdm/lightdm.conf
  sudo sed -i \
    -e "s@^\(user = \).\+@\1${USER}@" \
    -e "s@^\(show-password-label = \).\+@\1false@" \
    -e "s@^\(background-color = \).\+@\1\"#000000\"@;" \
    /etc/lightdm/lightdm-mini-greeter.conf

  # install misc programs
  yay --needed --noconfirm -S \
    slop feh maim ffmpeg zbar \
    keybase-bin pass pass-otp \
    neofetch glances inxi dfc youtube-dl \
    evince

  xdg-mime default evince.desktop application/pdf

  # install extra dependencies
  yay --needed --noconfirm -S python python-pygpgme    # polybar
  yay --needed --noconfirm -S xorg-xrandr              # bspwm

  # install crontab
  yay --needed --noconfirm -S cronie
  crontab ./crontab
  sudo systemctl enable cronie

  # raise inotify limit
  sudo tee -a /etc/sysctl.d/99-sysctl.conf <<<"fs.inotify.max_user_watches=524288"
}

update() {
  yay -Syu --noconfirm
}

link() {
  mklink xprofile ~/.xprofile
  mklink config/* $XDG_CONFIG_HOME/
  mklink fonts/* $XDG_DATA_HOME/fonts/
  mklink -s etc/pacman/*.hook /etc/pacman.d/hooks/
}

clean() {
  rm -fv $XDG_DATA_HOME/fonts/*(@N)
  sudo rm -fv /etc/pacman.d/hooks/*(@N)
}

init "$@"
