#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

install() {
  # Core essentials
  sudo pacman --needed --noconfirm -S wget git curl tree rsync dnsutils

  # Set up yay (AUR helper)
  if ! _is_callable yay; then
    git clone https://aur.archlinux.org/yay.git /tmp/yay
    cd /tmp/yay
    makepkg -sri --noconfirm --needed
    if ! _is_callable yay; then
        >&2 echo "Could not find pacaur"
        return 3
    fi
  fi

  yay --needed --noconfirm -S ripgrep the_silver_searcher bc
}

update() {
  _is_callable yay && local pac=yay
  ${pac:-sudo pacman} -Syu --noconfirm
}

# link() {}

# clean() {}

init "$@"
